name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  GH_WORKFLOW: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/imposd/llvm-ubuntu:latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up clang
      run: |
        apt-get update
        apt-get install -y --no-install-recommends clang-18
        if command -v clang-18 &> /dev/null; then
          echo "clang-18 installed successfully"
        else
          echo "clang-18 installation failed"
          exit 1
        fi

    - name: Set rustup version
      run: rustup default stable
    
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
