name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  GH_WORKFLOW: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get llvm-18 and clang-18
      run: |
        sudo apt-get update
        wget -qO llvm.sh https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18

        if command -v llvm-config-18 &> /dev/null && command -v clang-18 &> /dev/null; then
          echo "llvm-18 and clang-18 installed successfully"
        else
          echo "llvm-18 and/or clang-18 installation failed"
          exit 1
        fi

    - name: Set rustup version
      run: rustup default stable
    
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
